### ISSUE TITLE
how to shorten mention time?

### ISSUE THREAD

**Issue by solomon2544** [bbilly1/reddit-bot#2]
I'm such a noob so sorry in advance. I see you posted "the bot will search for new mentions every hour." but I was wondering if I can set it up so that it checks every 1 minute for the keywords im monitoring in the specific subreddit. 

Also would this script run on a raspberry pie?

**Comment by bbilly1** [comment]
I don't recommend spamming reddit like that, your IP is most likely going to be blocked pretty fast. I don't have plans to develop his much further, if you want to change things, you can do that yourself, that's why I open sourced it.

You can see on docker hub on the tags, that this is build for amd64/arm64, so newer PIs with 64 bit OS should be able to run it. 

EDIT Should have specified that: https://github.com/bbilly1/reddit-bot#about-this-project
